### ISSUE TITLE
Cannot uninstall 'certifi'. 

### ISSUE THREAD

**Issue by LiuTodd** [githublitao/api_automation_test#11]
运行pip install -r requirements.txt的时候出现：
Found existing installation: certifi 2018.4.16
Cannot uninstall 'certifi'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by LiuTaw** [comment]
我的环境是windows + anaconda3 python3.6.5 ，
