### ISSUE TITLE
你好，请教个问题

### ISSUE THREAD

**Issue by vinceny01** [githublitao/api_automation_test#17]
我站点搭建成功了，后台可以上的去，添加用户后，前台一直说账号或者密码错误，不知道该怎么解决，烦请看到后回复，谢谢

**Comment by githublitao** [comment]
因为你前端还是访问的我的后台，你在前端代码中，修改api.js里面的访问地址，然后重新npm run build打包就可以了

**Comment by vinceny01** [comment]
好的，非常感谢




| |
guo1144150162
邮箱：guo1144150162@163.com
|

Signature is customized by Netease Mail Master

在2018年10月25日 10:39，githublitao 写道：

因为你前端还是访问的我的后台，你在前端代码中，修改api.js里面的访问地址，然后重新npm run build打包就可以了
