### ISSUE TITLE
Amap引入问题

### ISSUE THREAD

**Issue by heylel** [githublitao/api_automation_test#18]
你好，请问地图定位服务是如何引入的。我复制你的login.vue也安装了vue-amap.但是一直提示找不到Amap组件。按网上的教程在index.html加了段引入webapi.amap的脚本<script>xxx</script>也无法定位成功

**Comment by githublitao** [comment]
地图定位只是我用来记录我体验地址的访客记录，作为自己使用，这个功能是没必要的
