### ISSUE TITLE
怎么把后端代码跑起来？

### ISSUE THREAD

**Issue by ChenYingqin** [githublitao/api_automation_test#20]
![image](https://user-images.githubusercontent.com/33275499/48174055-4da77680-e341-11e8-8d2a-60e7aebb6bde.png)    
![image](https://user-images.githubusercontent.com/33275499/48174156-c0b0ed00-e341-11e8-9d08-210a53dc2e2e.png)
![Uploading image.png…]()
api.js文件const test改成了我的ip后,向后端发http请求都是500的错误，后端代码没跑起来吗？

**Comment by ChenYingqin** [comment]
![image](https://user-images.githubusercontent.com/33275499/48183917-50b75c80-e36b-11e8-85ba-602010c8f837.png)
后台管理添加一个用户01，数据库已插入成功，但是服务器返回500错误，显示错误信息没有
api_test_userprofile这张数据库表，这个咋解决啊

**Comment by ChenYingqin** [comment]
![image](https://user-images.githubusercontent.com/33275499/48184027-abe94f00-e36b-11e8-8bb2-0425a60cce71.png)
![image](https://user-images.githubusercontent.com/33275499/48184050-c3c0d300-e36b-11e8-93e2-712c2b26f795.png)

**Comment by ChenYingqin** [comment]
![image](https://user-images.githubusercontent.com/33275499/48184486-25ce0800-e36d-11e8-9653-7687ee862db6.png)
怎么很多表都没有，是需要自己创建的吗，Python小白，大神帮帮忙这是什么原因啊

**Comment by ChenYingqin** [comment]
后台管理添加一个用户01，数据库已插入成功，但是服务器返回500错误，显示错误信息没有
api_test_userprofile这张数据库表，这个咋解决啊

**Comment by githublitao** [comment]
删除数据库，重新创建，用命令行，我文档中有写

**Comment by ChenYingqin** [comment]
![image](https://user-images.githubusercontent.com/33275499/48194783-e7464680-e388-11e8-8922-35203cf9244a.png)
![image](https://user-images.githubusercontent.com/33275499/48194797-f0371800-e388-11e8-93cf-6ac8074c485e.png)
![image](https://user-images.githubusercontent.com/33275499/48194960-69366f80-e389-11e8-8caa-c8dd60611af8.png)

前面执行都没问题了，执行最后一步打包命令cnpm run build,报很多错误，最后站点启动成功了，但是前端页面很混乱，这是怎么回事呢？

**Comment by ChenYingqin** [comment]
![image](https://user-images.githubusercontent.com/33275499/48195037-984ce100-e389-11e8-9762-7d88e2c4279e.png)
但是后端管理端功能正常

**Comment by ChenYingqin** [comment]
没想到重新删除frontend/node_modules文件，重新执行打包命令，终于可以了，感谢大神的项目，终于跑起来了啊

**Comment by lihuacai168** [comment]
> 没想到重新删除frontend/node_modules文件，重新执行打包命令，终于可以了，感谢大神的项目，终于跑起来了啊

我的管理页面是正常登录,但是用户登录页面是不能进入的.你的用户登录页面正常吗
