### ISSUE TITLE
配置完成后 http://127.0.0.1:8000/login 进入报错404

### ISSUE THREAD

**Issue by lihuacai168** [githublitao/api_automation_test#27]
http://127.0.0.1:8000/admin 是可以正常进入的.
管理后台的功能是正常的.
报错的图片如下.

![image](https://user-images.githubusercontent.com/11568297/50012011-7eda2d00-fff8-11e8-849c-5cb53c914dc4.png)
![image](https://user-images.githubusercontent.com/11568297/50043567-742f9e80-00b1-11e9-9032-6d26040a49e2.png)

在frontend目录下面build之后,没生成对应的静态文件呀,木有static目录

![c 3 _bm k _k up8 6hn84](https://user-images.githubusercontent.com/11568297/50055913-05754280-0190-11e9-88ab-0b75a4b3cb8c.png)

**Comment by lihuacai168** [comment]
重新部署了一遍.第十步前端打包那里不执行.直接启动django的服务.是访问ip:8000是可以进入登录页面.但是有个问题,在后台管理创建的用户,密码和用户都是正确的,但是提示用户名和密码错误.有点奇怪.
另外,如果进行了第十步,也就是打包之后.访问ip:8000就不能进入登录页面了.提示找不到上面图片的资源文件.

**Comment by githublitao** [comment]
改前端访问的域名，用uwsgi启动的话，静态文件要自己修改

**Comment by lihuacai168** [comment]
> 改前端访问的域名，用uwsgi启动的话，静态文件要自己修改

搞定了.是前端打包的时候,用国外的npm install导致 有些依赖没有下载.使用cnpm install就行.
