### ISSUE TITLE
求助求助，http请求设置Content-Type:application/json，请求一直错误

### ISSUE THREAD

**Issue by xlm1452** [githublitao/api_automation_test#3]
我在接口页面设置http的post请求，设置Content-Type:application/json，请求一直存在问题请求：
OPTIONS /osc/commands/execute HTTP/1.1不是post请求。而不设置该项请求能生效为post请求：
POST /osc/commands/execute HTTP/1.1，但json参数失败。是这个配置我有错误吗？

**Comment by githublitao** [comment]
最好贴图，不是很明白你的意思

在 2018-07-20 09:24:04，xlm1452 <notifications@github.com> 写道：


我在接口页面设置http的post请求，设置Content-Type:application/json，请求一直存在问题请求：
OPTIONS /osc/commands/execute HTTP/1.1不是post请求。而不设置该项请求能生效为post请求：
POST /osc/commands/execute HTTP/1.1，但json参数失败。是这个配置我有错误吗？

**Comment by xlm1452** [comment]
能加qq吗

**Comment by xlm1452** [comment]
我这边设置了Content-Type:application/json，请求如下：
![image](https://user-images.githubusercontent.com/40480581/43069601-19a9b9c4-8ea0-11e8-9f72-4f53e096c202.png)
如果没有设置，请求是post请求：
![image](https://user-images.githubusercontent.com/40480581/43069666-42caaf02-8ea0-11e8-8754-039c390f2aa8.png)

**Comment by githublitao** [comment]
那就叫开发设置跨域请求吧



在 2018-08-20 13:19:13，"huhust" <notifications@github.com> 写道：


排查了好久，原来是跨域的问题。。。。。。
快速测试那边是用的ajax请求，存在跨域问题会被拦截掉，所以POST请求在Fiddler上会显示成options
用项目自己的接口（同域）测试了，没有问题

**Comment by huhust** [comment]
还有一种方案，就是在项目里面自己开一个接口，用request请求接口，现在准备搞一下试试
