### ISSUE TITLE
前端权限认证问题

### ISSUE THREAD

**Issue by cyrus1900** [githublitao/api_automation_test#38]
后台添加的用户无法在前端登录 提示用户名或密码错误
![admin](https://user-images.githubusercontent.com/38196191/55709682-71b7d280-5a1b-11e9-983a-ed3545bfba8c.png)

**Comment by cyrus1900** [comment]
![user](https://user-images.githubusercontent.com/38196191/55709882-e3901c00-5a1b-11e9-86e1-7b6423945b5c.png)

**Comment by cyrus1900** [comment]
![db](https://user-images.githubusercontent.com/38196191/55710048-50a3b180-5a1c-11e9-875d-e5c4c4ed952c.png)

**Comment by githublitao** [comment]
确认前端请求的域名是否是你的服务器，如果不是，修改域名，重新打包，api.js文件内

**Comment by cyrus1900** [comment]
请问在哪个文件中修改  我是新手 麻烦您说的清晰一点谢谢！

**Comment by cyrus1900** [comment]
![api](https://user-images.githubusercontent.com/38196191/55711359-1851a280-5a1f-11e9-9073-a0a1217bdc9a.png)
是这里吗？

**Comment by githublitao** [comment]
是的，现在访问的是我的体验服务器，改成自己的域名

**Comment by cyrus1900** [comment]
解决了 谢谢大佬
