### ISSUE TITLE
请求项目列表参数问题

### ISSUE THREAD

**Issue by cyrus1900** [githublitao/api_automation_test#39]
![项目列表](https://user-images.githubusercontent.com/38196191/55713175-b135ed00-5a22-11e9-878c-90f7c8fb5ef5.png)
请求项目列表的name参数为空 返回500

**Comment by cyrus1900** [comment]
![1](https://user-images.githubusercontent.com/38196191/55713301-f8bc7900-5a22-11e9-9a4f-d123dce4aa45.png)

**Comment by cyrus1900** [comment]
我建的用户有first name 啊

**Comment by githublitao** [comment]
数据库重新构建
