### ISSUE TITLE
您好, 可以给个校验规则的示例代码吗?不是很清楚该怎么写?

### ISSUE THREAD

**Issue by leo2n** [githublitao/api_automation_test#4]
您好, 可以给个校验规则的示例代码吗?比如说: 我使用一个http get方法后, 返回的结果是: {"msg": "success", "code": 8001""}, 如果需要校验这两项的键值对, 应该怎么做呢?

**Comment by githublitao** [comment]
json只校验json格式，正则校验，输入正则表达式，内部用的finadll进行匹配，如果匹配有内容，则校验成功，你现在的需求需要校验键和值，则可以使用完全校验， 内容输入{"msg": "success", "code": 8001"}就行了，注意空格

**Comment by leo2n** [comment]
好的, 非常感谢您!

**Comment by leo2n** [comment]
您好, 可以给一个正则校验的示例吗?例如, 返回结果是: {"hello": "yes", "msg": "good", "code": "8001"}, 我需要检测code的对应的值和msg对应的值, 请问这个该如何做呢?

**Comment by githublitao** [comment]
代码中就是用finall根据这个正则表达式去匹配数据
