### ISSUE TITLE
api接口 一个接口执行测试后其他接口的参数信息丢失

### ISSUE THREAD

**Issue by cyrus1900** [githublitao/api_automation_test#42]
![param](https://user-images.githubusercontent.com/38196191/55780869-822f8200-5adb-11e9-9394-ad62b68207aa.png)
不同分组的多个接口 其中一个接口执行测试后 其他接口的参数信息全部丢失

**Comment by githublitao** [comment]
你可以在体验服务器上重现一下，如果仍然有问题，再提

**Comment by cyrus1900** [comment]
![2](https://user-images.githubusercontent.com/38196191/55781537-eef74c00-5adc-11e9-8f36-ff9ea55443cf.png)
只要 接口设成 get https 后就会这样
