### ISSUE TITLE
api接口 修改一个接口的参数信息 其他接口的参数信息全部丢失

### ISSUE THREAD

**Issue by cyrus1900** [githublitao/api_automation_test#43]
![2](https://user-images.githubusercontent.com/38196191/55782267-78f3e480-5ade-11e9-88fd-32a0398c3377.png)
已经在测试服务器中测试过  新建3个api接口 修改其中一个接口的参数信息 其他接口的参数信息全部丢失

**Comment by cyrus1900** [comment]
经过大量测试 api 接口信息的修改功能存在严重问题 会导致全部接口信息参数丢失 希望尽快验证bug

**Comment by cyrus1900** [comment]
![数据库](https://user-images.githubusercontent.com/38196191/55787371-b493ac00-5ae8-11e9-8299-6c1914c46d50.png)

**Comment by cyrus1900** [comment]
执行修改操作后数据库参数表只剩修改的参数

**Comment by githublitao** [comment]
已修复
