### ISSUE TITLE
项目不错，是否可以支持以下功能，多谢

### ISSUE THREAD

**Issue by oopsky** [githublitao/api_automation_test#44]
打算要开发一个类似的接口测试平台，在这里看到这个项目，感觉项目不错，是否可以支持以下功能，多谢。如果认可的话，我希望能参与进来一起完善功能（不限于以下功能）。

1. HOST支持配置域名对应的IP和端口，IP和端口可为空
2. 测试环境也可以分组，支持选择多个测试环境批量执行；
3. 增加基于用例分组的测试报告，增加邮件发送测试报告；
4. 进入项目后，不隐藏左侧导航栏，方便切换；
5. 账号注册，权限;

**Comment by githublitao** [comment]
1，2，3支持，4不太明白你要什么，5不支持注册，只能有后台添加新用户，权限这块还没加

**Comment by oopsky** [comment]
1,2,3目前怎么操作，从demo的系统http://120.79.232.23/里面没有看到.
HOST与IP关联支持：当前可以通过设置header来实现映射。，我是希望可以在测试环境这里配置好，被选中接口可以在指定的测试环境进行测试。比如www.test.com这个域名最好可以设置多个测试环境，分别指向IP 10.10.120.2（默认端口80）、10.10.120.3（端口443）、10.10.120.4（端口3450）。

环境批量执行：比如以上的环境可以批量同时执行，目前是下拉列表单选一个环境执行的。希望可以下拉列表可以做成复选框的，查询结果的时候，也可以按照测试环境进行检查接口执行结果。

第4，不算是个问题，只是我个人的使用体验。 点击项目名称的时候弹出新窗口。是指进入自动化测试页面后，左侧的项目导航栏不显示，不方便切换到其他的项目。

**Comment by githublitao** [comment]
并没有做得那么复杂，你可以自己弄一下

**Comment by oopsky** [comment]
好的，多谢
