### ISSUE TITLE
"该操作只能在Linux系统下进行"，定时任务不支持部署在windows么？

### ISSUE THREAD

**Issue by broardshore** [githublitao/api_automation_test#50]
我的项目是部署在windows server服务器的，想要用定时任务只能改用linux服务器么？

**Comment by githublitao** [comment]
定时任务模块，是往Linux下的crontab里面插入一条执行用例的任务，我不太了解Windowsserver系统，你可以自己去了解一下这个系统有没有类似的模块，通过获取当前系统类型，自己添加一块代码完成

**Comment by CL0406** [comment]
![image](https://user-images.githubusercontent.com/45259520/61110291-893ea580-a4b9-11e9-9d82-c0a683913eb2.png)
这是你原本的代码，请问一下这里是怎么回事咧？
我在windows环境下执行就不会在这里出错，在linux运行的时候就报错了。

**Comment by CL0406** [comment]
> 定时任务模块，是往的Linux下的crontab的里面插入一条执行用例的任务，我不太了解的WindowsServer系统，你可以自己去了解一下这个系统有没有类似的模块，通过获取当前系统类型，自己添加一块代码完成
![image](https://user-images.githubusercontent.com/45259520/61110390-c440d900-a4b9-11e9-82d9-df28545ff891.png)
这是你原本的代码，请问一下这里是怎么回事咧？
我在窗口环境下执行就不会在这里出错，在linux下运行的时候就报错了。

**Comment by StayingHungry** [comment]
‘是往Linux下的crontab里面插入一条执行用例的任务’  

> 定时任务模块，是往Linux下的crontab里面插入一条执行用例的任务，我不太了解Windowsserver系统，你可以自己去了解一下这个系统有没有类似的模块，通过获取当前系统类型，自己添加一块代码完成

如果定时任务特别多的话（上万条），用crontab还ok吗?

**Comment by githublitao** [comment]
不清楚，但如果公司需要并行这么多任务的话，当然也会投入资金自己研发一套

**Comment by CL0406** [comment]
windows的话你可以使用celery+rabbitMQ来做呀
