### ISSUE TITLE
无法进行mock

### ISSUE THREAD

**Issue by ZhuangDongFa** [githublitao/api_automation_test#52]
![image](https://user-images.githubusercontent.com/22289983/58091022-2c321c00-7bfb-11e9-8d6f-419aebd7e04c.png)
![image](https://user-images.githubusercontent.com/22289983/58091054-3d7b2880-7bfb-11e9-879a-7fd75f3c82bb.png)
第一张图系统的请求参数为{'name': 'aaa', 'key': 'bbb'}，json是双引号的为{"name": "aaa", "key": "bbb"}。所以导致测试接口的时候返回了参数有误。
进入mock发送单引号时报错，发送信息为双引号时正常通过

**Comment by githublitao** [comment]
你是打算让我兼容单引号？

**Comment by ZhuangDongFa** [comment]
![image](https://user-images.githubusercontent.com/22289983/58161985-e08f7900-7cb3-11e9-914f-c55915defc21.png)
我请求时已经就是双引号了，但是发起请求时参数显示的是单引号。然后接口返回结果就为参数有误了

**Comment by githublitao** [comment]
嗦嘎，小问题

**Comment by ZhuangDongFa** [comment]
是mock模式的

**Comment by ZhuangDongFa** [comment]
还有一个严重的问题，就是失败的测试结果无法进行查看。
![image](https://user-images.githubusercontent.com/22289983/58162288-817e3400-7cb4-11e9-8640-c32c3f61ddc8.png)
有时候一些成功的或者失败的测试结果无法点击查看
![image](https://user-images.githubusercontent.com/22289983/58162328-95299a80-7cb4-11e9-9483-e72e21b976a4.png)

**Comment by githublitao** [comment]
我建议你使用httprunner，这个平台，比较成熟

**Comment by ZhuangDongFa** [comment]
目前就有这两个问题比较严重，我都快放弃治疗了。。联系不到您，以后您放弃这个项目了。您能创建一个问题群吗。大家有问题可以第一时间联系。

**Comment by ZhuangDongFa** [comment]
好的，谢谢，我接触一下看看。万分感谢。目前公司需要一个接口测试平台。

**Comment by githublitao** [comment]
算了吧，我确实放弃了这个项目。为了长远发展，建议你使用httprunner

**Comment by ZhuangDongFa** [comment]
好的，谢谢您。请问您有交流学习群吗？

**Comment by githublitao** [comment]
没有哇
