### ISSUE TITLE
python manage.py makemigrations执行报错

### ISSUE THREAD

**Issue by phonix512** [githublitao/api_automation_test#56]
第5步python manage.py makemigrations报错django.db.utils.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: NO)")

**Comment by 418926059** [comment]
高版本sql加密规则变了  django用的是旧加密规则，登入mysql后 UPDATE user SET authentication_string=PASSWORD('newpassword') where USER='root';

**Comment by phonix512** [comment]
> 
> 
> 高版本sql加密规则变了 django用的是旧加密规则，登入mysql后 UPDATE user SET authentication_string=PASSWORD('newpassword') where USER='root';

OK，谢谢了
