### ISSUE TITLE
请问随便新增一个get请求都报错，跨域的问题，怎么解决？？

### ISSUE THREAD

**Issue by diandianxing** [githublitao/api_automation_test#65]
新增了一个get请求，console报错信息如下：
Access to XMLHttpRequest at 'https://www.cnblogs.com/litings/p/9700040.html?=&=' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Cross-Origin Read Blocking (CORB) blocked cross-origin response https://www.cnblogs.com/litings/p/9700040.html?=&= with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.

求解决方案？

**Comment by gggcgba** [comment]
ImportError: cannot import name 'VERSION' from 'suit' (C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\suit\__init__.py)
这个怎么解决呢？

**Comment by githublitao** [comment]
卸载库，按 说明重装
