### ISSUE TITLE
执行测试用例后，查看详情页面无法点击，js报错

### ISSUE THREAD

**Issue by pf102030** [githublitao/api_automation_test#77]

**Comment by citymyname** [comment]
发送api请求后为什么没有显示响应内容呢

**Comment by githublitao** [comment]
可能是跨域问题

**Comment by citymyname** [comment]
![FFFE7869-6B19-4AB4-9168-85F47AEAB81E](https://user-images.githubusercontent.com/59354560/94523856-65a17f80-0264-11eb-959b-6d8a57626d9c.png)
请问下响应体为0是什么

**Comment by githublitao** [comment]
这个不清楚了，需要调试一下

**Comment by citymyname** [comment]
我看了，应该是请求数据格式不对，这个请求需要使用json格式，那个是使用表单的。
请问怎么设置json格式的请求，多谢！

**Comment by citymyname** [comment]
在请求头加Content-Type:pplication/json就可以了吧
