### ISSUE TITLE
导出来的测试用例，为什么前缀都是http://xxxx，这个是默认写死了吗，因为配置host也没用

### ISSUE THREAD

**Issue by HEhunter** [githublitao/api_automation_test#81]

**Comment by githublitao** [comment]
写死了

**Comment by HEhunter** [comment]
老铁，这个是否可以修改一下，让我们体验一波，感谢





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "githublitao/api_automation_test"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月10日(星期二) 下午4:03
收件人:&nbsp;"githublitao/api_automation_test"<api_automation_test@noreply.github.com&gt;;
抄送:&nbsp;"小明伟"<978906462@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [githublitao/api_automation_test] 导出来的测试用例，为什么前缀都是http://xxxx，这个是默认写死了吗，因为配置host也没用 (#81)





 
写死了
